server:
  port: 8080

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: beans, health, loggers
    health:
      enabled: true
    loggers:
      enabled: true
    beans:
      enabled: true
    liquibase:
      enabled: true
    git:
      enbled: true

logging:
  level.root: INFO
  #  level.org.hibernate.SQL: DEBUG
  level.liquibase: INFO
  level.io.fdlessard.codebites.customer: DEBUG

spring:
  application:
    name: customer-application
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
    serialization:
      write_dates_as_timestamps: false
  datasource:
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret}
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:postgres}
    initialization-mode: always
  liquibase:
    enabled: on
    drop-first: on
    default-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      jdbc:
        time_zone: UTC
    show-sql: true


